### ISSUE TITLE
Update CI jobs with Docker Login [DATALDAP-184]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-ldap#203]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATALDAP-184](https://jira.spring.io/browse/DATALDAP-184?redirect=false)** and commented

---
No further details from [DATALDAP-184](https://jira.spring.io/browse/DATALDAP-184?redirect=false)

**Comment by gregturn** [comment]
Superceded by usage of VMW Harbor for Docker proxy support on CI. (#301
