### ISSUE TITLE
Binary attributes are converted to string when queried by

### ISSUE THREAD

**Issue by goto1134** [spring-projects/spring-data-ldap#320]
I have the following Entity

```kotlin
@Entry(objectClasses = ["top", "person", "user"], base = "ou=users")
class LdapUser {

    @Id
    lateinit var id: Name

    @Attribute(name = "objectGUID", type = Attribute.Type.BINARY, readonly = true)
    lateinit var guid: ByteArray
}

interface LdapUserRepository : Repository<LdapUser, Name> {
    fun findByGuid(guid: ByteArray): AlternativeLdapUser
}
```

When I search by guid with value `90d1c68e-01be-4485-aafd-b3ffb9ddb026` converted to a 32 element byte array, the library generates the following request:

`base=ou=users, finalFilter=(&(&(objectclass=top)(objectclass=person)(objectclass=user))(objectGUID=[B@7363e35b))`

And the result is always empty. The correct filter would be:

`base=ou=users, finalFilter=(&(&(objectclass=top)(objectclass=person)(objectclass=user))(objectGUID=\90\d1\c6\8e\01\be\44\85\aa\fd\b3\ff\b9\dd\b0\26))`

Please, support binary attribute query parameters.

**Comment by goto1134** [comment]
This issue may be somehow related to https://github.com/spring-projects/spring-ldap/issues/634

**Comment by mp911de** [comment]
`ConditionCriteria` supports only `String` arguments. We can proceed here once Spring LDAP accepts other value types.

**Comment by mp911de** [comment]
We've introduced `@LdapEncode` annotations to control the representation. You can now implement an LDAP encoder to represent your UUID as base64-encoded string. Since LDAP queries are strings anyways, all arguments are converted into their `toString` representation.
