### ISSUE TITLE
Fix broken links in reference documentation

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-ldap#364]
```
404 NOT_FOUND: https://docs.spring.io/spring/docs/6.0.0/spring-framework-reference/core.html
404 NOT_FOUND: https://docs.spring.io/spring/docs/6.0.0/spring-framework-reference/core.html#beans
404 NOT_FOUND: https://docs.spring.io/spring/docs/6.0.0/spring-framework-reference/core.html#validation
404 NOT_FOUND: https://docs.spring.io/spring/docs/6.0.0/spring-framework-reference/core.html#expressions
404 NOT_FOUND: https://docs.spring.io/spring/docs/6.0.0/spring-framework-reference/core.html#aop
404 NOT_FOUND: https://docs.spring.io/spring/docs/6.0.0/spring-framework-reference/integration.html#jmx
404 NOT_FOUND: https://docs.spring.io/spring/docs/6.0.0/spring-framework-reference/data-access.html
404 NOT_FOUND: https://docs.spring.io/spring/docs/6.0.0/spring-framework-reference/data-access.html#dao-exceptions
404 NOT_FOUND: https://docs.spring.io/spring/docs/6.0.0/spring-framework-reference/
```

**Comment by Lostmaniac9** [comment]
Provided I am understanding all of this right, these are the corrected links in order for what is commented above. "\spring-framework-reference" no longer exists and has been replaced by "\reference\html".

https://docs.spring.io/spring-framework/docs/6.0.0/reference/html/core.html
https://docs.spring.io/spring-framework/docs/6.0.0/reference/html/core.html#beans
https://docs.spring.io/spring-framework/docs/6.0.0/reference/html/core.html#validation
https://docs.spring.io/spring-framework/docs/6.0.0/reference/html/core.html#expressions
https://docs.spring.io/spring-framework/docs/6.0.0/reference/html/core.html#aop
https://docs.spring.io/spring-framework/docs/6.0.0/reference/html/integration.html#jmx
https://docs.spring.io/spring-framework/docs/6.0.0/reference/html/data-access.html
https://docs.spring.io/spring-framework/docs/6.0.0/reference/html/data-access.html#dao-exceptions
https://docs.spring.io/spring-framework/docs/6.0.0/reference/html/
