### ISSUE TITLE
How to add and objectClass dynamically

### ISSUE THREAD

**Issue by oscarbrookssynacor** [spring-projects/spring-data-ldap#448]
Hello, I am trying to accomplish the following: 
```
@Data
@Entry(base = "", objectClasses = { "SomeObjectClass" })
public class SomeEntry {
    private @Attribute(name = "objectClass") List<String> objectClasses;
    private @Attribute(name = "attributeRequiredByOtherObjectClass") String someAttribute;
}


SomeEntry entry =  someEntryRepository.findBy...(...);
entry.getObjectClasses().add("OtherObjectClass");
entry.setSomeAttribute("Value")
someEntryRepository.save(entry);
```
Currently I am getting an error 
```
javax.naming.directory.SchemaViolationException: [LDAP: error code 65 - attribute 'attributeRequiredByOtherObjectClass' not allowed]
```

If I perform the same operation on an entry that already has the objectClass "OtherObjectClass" the operation succeeds. 
Hopefully someone can guide me to the correct way to do this. Thanks in advance!

**Comment by oscarbrookssynacor** [comment]
Update: 
After some looking it appears that this is the line responsible for this issue: 
https://github.com/spring-projects/spring-ldap/blob/16f2626a4d388486cc7f49b6e5cc8aaeaccb3ec5/core/src/main/java/org/springframework/ldap/odm/core/impl/DefaultObjectDirectoryMapper.java#L164

**Comment by oscarbrookssynacor** [comment]
To clarify, this seems like a bug, since I am able to accomplish this the following way: 
```
entry.getObjectClasses().add("OtherObjectClass");
DirContextOperations context = ldapTemplate.lookupContext(entry.getId());
context.setAttributeValues("objectClass", domainEntry.getObjectClass().toArray());
context.setAttributeValue("attributeRequiredByOtherObjectClass", domainEntry.getSomeAttribute());
ldapTemplate.update(domainEntry);
```

**Comment by mp911de** [comment]
Thanks for reaching out. Spring Data LDAP is a tiny extension on top of Spring LDAP. We don't add much functionality beyond loading and saving, all object mapping is handled by Spring LDAP as well. Care to file a bug in Spring LDAP as the mentioned class stems from that project?

**Comment by oscarbrookssynacor** [comment]
I already did, here it is for future reference: 
https://github.com/spring-projects/spring-ldap/issues/835

thanks for the quick reply.
